language: elixir
elixir:
  - 1.10.2
  - 1.9.4
  - 1.8.1
  - 1.7.4
otp_release:
  - 21.3.8

services:
  - postgresql

before_script:
  - mix compile --warnings-as-errors
  - if elixir --version | grep -q 1.8; then mix format --check-formatted; fi
  - mix ecto.setup
